# Generated by Django 4.2.4 on 2023-09-05 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kitties', '0002_remove_kitties_photo_remove_kitties_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitties',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
    ]
